//! Closed QK-DEC-144 shell and peer-rejection vocabulary.

use core::fmt;
use qk_ipc::IpcError;

/// Exact terminating interruption reasons shared with the v2 shell topology.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Interruption {
    Cancelled,
    OperationFailed,
    MediaRemoved,
    CardRemoved,
    SessionTimeout,
    Shutdown,
    Restart,
    PowerLoss,
    PeerLost,
    CapabilityFailed,
}

impl Interruption {
    /// Stable non-hostile name.
    pub const fn name(self) -> &'static str {
        match self {
            Self::Cancelled => "Cancelled",
            Self::OperationFailed => "OperationFailed",
            Self::MediaRemoved => "MediaRemoved",
            Self::CardRemoved => "CardRemoved",
            Self::SessionTimeout => "SessionTimeout",
            Self::Shutdown => "Shutdown",
            Self::Restart => "Restart",
            Self::PowerLoss => "PowerLoss",
            Self::PeerLost => "PeerLost",
            Self::CapabilityFailed => "CapabilityFailed",
        }
    }
}

impl fmt::Display for Interruption {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.name())
    }
}

/// Independently mapped QK-DEC-143 peer-rejection names.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum IoRejection {
    InnerHeaderTruncated,
    InnerVersionMismatch,
    RequestReservedNonZero,
    OperationOutOfRange,
    BodyLengthExceeded,
    BodyTruncated,
    TrailingByte,
    UnexpectedBoundary,
    BoundaryMissing,
    SourceKindMismatch,
    SourceAlreadyUsed,
    WriterKindMismatch,
    WriterAlreadyUsed,
    ActiveTransfer,
    NoActiveTransfer,
    WrongTransferDirection,
    SourceLengthMismatch,
    DeclaredLengthZero,
    DeclaredLengthExceeded,
    OffsetMismatch,
    ChunkLengthZero,
    ChunkLengthExceeded,
    TransferLengthExceeded,
    TransferIncomplete,
    SourceOutOfRange,
    SinkOutOfRange,
    ArtifactOutOfRange,
    SinkArtifactMismatch,
    InvalidFilename,
    InvalidBbqrPartLength,
    AllocationFailed,
    SourceReadFailed,
    OutputCollision,
    OutputCreateFailed,
    OutputWriteFailed,
    OutputSyncFailed,
    OutputCloseFailed,
    OutputReopenFailed,
    OutputReadbackMismatch,
    OutputRenameFailed,
    PrintFailed,
    EmptyPayload,
    PayloadTooLarge,
    InvalidNonFinalPartLength,
    TooManyParts,
    PartIndexOutOfRange,
    FrameTooShort,
    FrameTooLarge,
    InvalidMagic,
    UnsupportedEncoding,
    UnsupportedFileType,
    InvalidDeclaredPartCount,
    DeclaredPartCountExceeded,
    InvalidPartIndex,
    EmptyPart,
    Base32PaddingForbidden,
    MalformedBase32Symbol,
    NonCanonicalBase32Length,
    NonCanonicalBase32Padding,
    NonFinalPartLengthNotMultipleOfFive,
    StreamEncodingMismatch,
    StreamFileTypeMismatch,
    StreamPartCountMismatch,
    NonUniformPartLength,
    FinalPartTooLarge,
    TotalDecodedSizeExceeded,
    ConflictingDuplicate,
    DuplicateWorkExceeded,
    SubmissionWorkExceeded,
    Incomplete,
    AlreadyComplete,
}

impl IoRejection {
    pub(crate) const fn from_status(status: u16) -> Option<Self> {
        match status {
            0x0001 => Some(Self::InnerHeaderTruncated),
            0x0002 => Some(Self::InnerVersionMismatch),
            0x0003 => Some(Self::RequestReservedNonZero),
            0x0004 => Some(Self::OperationOutOfRange),
            0x0005 => Some(Self::BodyLengthExceeded),
            0x0006 => Some(Self::BodyTruncated),
            0x0007 => Some(Self::TrailingByte),
            0x0008 => Some(Self::UnexpectedBoundary),
            0x0009 => Some(Self::BoundaryMissing),
            0x000a => Some(Self::SourceKindMismatch),
            0x000b => Some(Self::SourceAlreadyUsed),
            0x000c => Some(Self::WriterKindMismatch),
            0x000d => Some(Self::WriterAlreadyUsed),
            0x000e => Some(Self::ActiveTransfer),
            0x000f => Some(Self::NoActiveTransfer),
            0x0010 => Some(Self::WrongTransferDirection),
            0x0011 => Some(Self::SourceLengthMismatch),
            0x0012 => Some(Self::DeclaredLengthZero),
            0x0013 => Some(Self::DeclaredLengthExceeded),
            0x0014 => Some(Self::OffsetMismatch),
            0x0015 => Some(Self::ChunkLengthZero),
            0x0016 => Some(Self::ChunkLengthExceeded),
            0x0017 => Some(Self::TransferLengthExceeded),
            0x0018 => Some(Self::TransferIncomplete),
            0x0019 => Some(Self::SourceOutOfRange),
            0x001a => Some(Self::SinkOutOfRange),
            0x001b => Some(Self::ArtifactOutOfRange),
            0x001c => Some(Self::SinkArtifactMismatch),
            0x001d => Some(Self::InvalidFilename),
            0x001e => Some(Self::InvalidBbqrPartLength),
            0x001f => Some(Self::AllocationFailed),
            0x0020 => Some(Self::SourceReadFailed),
            0x0021 => Some(Self::OutputCollision),
            0x0022 => Some(Self::OutputCreateFailed),
            0x0023 => Some(Self::OutputWriteFailed),
            0x0024 => Some(Self::OutputSyncFailed),
            0x0025 => Some(Self::OutputCloseFailed),
            0x0026 => Some(Self::OutputReopenFailed),
            0x0027 => Some(Self::OutputReadbackMismatch),
            0x0028 => Some(Self::OutputRenameFailed),
            0x0029 => Some(Self::PrintFailed),
            0x0101 => Some(Self::EmptyPayload),
            0x0102 => Some(Self::PayloadTooLarge),
            0x0103 => Some(Self::InvalidNonFinalPartLength),
            0x0104 => Some(Self::TooManyParts),
            0x0105 => Some(Self::PartIndexOutOfRange),
            0x0106 => Some(Self::FrameTooShort),
            0x0107 => Some(Self::FrameTooLarge),
            0x0108 => Some(Self::InvalidMagic),
            0x0109 => Some(Self::UnsupportedEncoding),
            0x010a => Some(Self::UnsupportedFileType),
            0x010b => Some(Self::InvalidDeclaredPartCount),
            0x010c => Some(Self::DeclaredPartCountExceeded),
            0x010d => Some(Self::InvalidPartIndex),
            0x010e => Some(Self::EmptyPart),
            0x010f => Some(Self::Base32PaddingForbidden),
            0x0110 => Some(Self::MalformedBase32Symbol),
            0x0111 => Some(Self::NonCanonicalBase32Length),
            0x0112 => Some(Self::NonCanonicalBase32Padding),
            0x0113 => Some(Self::NonFinalPartLengthNotMultipleOfFive),
            0x0114 => Some(Self::StreamEncodingMismatch),
            0x0115 => Some(Self::StreamFileTypeMismatch),
            0x0116 => Some(Self::StreamPartCountMismatch),
            0x0117 => Some(Self::NonUniformPartLength),
            0x0118 => Some(Self::FinalPartTooLarge),
            0x0119 => Some(Self::TotalDecodedSizeExceeded),
            0x011a => Some(Self::ConflictingDuplicate),
            0x011b => Some(Self::DuplicateWorkExceeded),
            0x011c => Some(Self::SubmissionWorkExceeded),
            0x011d => Some(Self::Incomplete),
            0x011e => Some(Self::AlreadyComplete),
            _ => None,
        }
    }

    /// Exact nonzero QK-DEC-143 status code.
    pub const fn status_code(self) -> u16 {
        match self {
            Self::InnerHeaderTruncated => 0x0001,
            Self::InnerVersionMismatch => 0x0002,
            Self::RequestReservedNonZero => 0x0003,
            Self::OperationOutOfRange => 0x0004,
            Self::BodyLengthExceeded => 0x0005,
            Self::BodyTruncated => 0x0006,
            Self::TrailingByte => 0x0007,
            Self::UnexpectedBoundary => 0x0008,
            Self::BoundaryMissing => 0x0009,
            Self::SourceKindMismatch => 0x000a,
            Self::SourceAlreadyUsed => 0x000b,
            Self::WriterKindMismatch => 0x000c,
            Self::WriterAlreadyUsed => 0x000d,
            Self::ActiveTransfer => 0x000e,
            Self::NoActiveTransfer => 0x000f,
            Self::WrongTransferDirection => 0x0010,
            Self::SourceLengthMismatch => 0x0011,
            Self::DeclaredLengthZero => 0x0012,
            Self::DeclaredLengthExceeded => 0x0013,
            Self::OffsetMismatch => 0x0014,
            Self::ChunkLengthZero => 0x0015,
            Self::ChunkLengthExceeded => 0x0016,
            Self::TransferLengthExceeded => 0x0017,
            Self::TransferIncomplete => 0x0018,
            Self::SourceOutOfRange => 0x0019,
            Self::SinkOutOfRange => 0x001a,
            Self::ArtifactOutOfRange => 0x001b,
            Self::SinkArtifactMismatch => 0x001c,
            Self::InvalidFilename => 0x001d,
            Self::InvalidBbqrPartLength => 0x001e,
            Self::AllocationFailed => 0x001f,
            Self::SourceReadFailed => 0x0020,
            Self::OutputCollision => 0x0021,
            Self::OutputCreateFailed => 0x0022,
            Self::OutputWriteFailed => 0x0023,
            Self::OutputSyncFailed => 0x0024,
            Self::OutputCloseFailed => 0x0025,
            Self::OutputReopenFailed => 0x0026,
            Self::OutputReadbackMismatch => 0x0027,
            Self::OutputRenameFailed => 0x0028,
            Self::PrintFailed => 0x0029,
            Self::EmptyPayload => 0x0101,
            Self::PayloadTooLarge => 0x0102,
            Self::InvalidNonFinalPartLength => 0x0103,
            Self::TooManyParts => 0x0104,
            Self::PartIndexOutOfRange => 0x0105,
            Self::FrameTooShort => 0x0106,
            Self::FrameTooLarge => 0x0107,
            Self::InvalidMagic => 0x0108,
            Self::UnsupportedEncoding => 0x0109,
            Self::UnsupportedFileType => 0x010a,
            Self::InvalidDeclaredPartCount => 0x010b,
            Self::DeclaredPartCountExceeded => 0x010c,
            Self::InvalidPartIndex => 0x010d,
            Self::EmptyPart => 0x010e,
            Self::Base32PaddingForbidden => 0x010f,
            Self::MalformedBase32Symbol => 0x0110,
            Self::NonCanonicalBase32Length => 0x0111,
            Self::NonCanonicalBase32Padding => 0x0112,
            Self::NonFinalPartLengthNotMultipleOfFive => 0x0113,
            Self::StreamEncodingMismatch => 0x0114,
            Self::StreamFileTypeMismatch => 0x0115,
            Self::StreamPartCountMismatch => 0x0116,
            Self::NonUniformPartLength => 0x0117,
            Self::FinalPartTooLarge => 0x0118,
            Self::TotalDecodedSizeExceeded => 0x0119,
            Self::ConflictingDuplicate => 0x011a,
            Self::DuplicateWorkExceeded => 0x011b,
            Self::SubmissionWorkExceeded => 0x011c,
            Self::Incomplete => 0x011d,
            Self::AlreadyComplete => 0x011e,
        }
    }

    /// Stable non-hostile mapped name.
    pub const fn name(self) -> &'static str {
        match self {
            Self::InnerHeaderTruncated => "InnerHeaderTruncated",
            Self::InnerVersionMismatch => "InnerVersionMismatch",
            Self::RequestReservedNonZero => "RequestReservedNonZero",
            Self::OperationOutOfRange => "OperationOutOfRange",
            Self::BodyLengthExceeded => "BodyLengthExceeded",
            Self::BodyTruncated => "BodyTruncated",
            Self::TrailingByte => "TrailingByte",
            Self::UnexpectedBoundary => "UnexpectedBoundary",
            Self::BoundaryMissing => "BoundaryMissing",
            Self::SourceKindMismatch => "SourceKindMismatch",
            Self::SourceAlreadyUsed => "SourceAlreadyUsed",
            Self::WriterKindMismatch => "WriterKindMismatch",
            Self::WriterAlreadyUsed => "WriterAlreadyUsed",
            Self::ActiveTransfer => "ActiveTransfer",
            Self::NoActiveTransfer => "NoActiveTransfer",
            Self::WrongTransferDirection => "WrongTransferDirection",
            Self::SourceLengthMismatch => "SourceLengthMismatch",
            Self::DeclaredLengthZero => "DeclaredLengthZero",
            Self::DeclaredLengthExceeded => "DeclaredLengthExceeded",
            Self::OffsetMismatch => "OffsetMismatch",
            Self::ChunkLengthZero => "ChunkLengthZero",
            Self::ChunkLengthExceeded => "ChunkLengthExceeded",
            Self::TransferLengthExceeded => "TransferLengthExceeded",
            Self::TransferIncomplete => "TransferIncomplete",
            Self::SourceOutOfRange => "SourceOutOfRange",
            Self::SinkOutOfRange => "SinkOutOfRange",
            Self::ArtifactOutOfRange => "ArtifactOutOfRange",
            Self::SinkArtifactMismatch => "SinkArtifactMismatch",
            Self::InvalidFilename => "InvalidFilename",
            Self::InvalidBbqrPartLength => "InvalidBbqrPartLength",
            Self::AllocationFailed => "AllocationFailed",
            Self::SourceReadFailed => "SourceReadFailed",
            Self::OutputCollision => "OutputCollision",
            Self::OutputCreateFailed => "OutputCreateFailed",
            Self::OutputWriteFailed => "OutputWriteFailed",
            Self::OutputSyncFailed => "OutputSyncFailed",
            Self::OutputCloseFailed => "OutputCloseFailed",
            Self::OutputReopenFailed => "OutputReopenFailed",
            Self::OutputReadbackMismatch => "OutputReadbackMismatch",
            Self::OutputRenameFailed => "OutputRenameFailed",
            Self::PrintFailed => "PrintFailed",
            Self::EmptyPayload => "EmptyPayload",
            Self::PayloadTooLarge => "PayloadTooLarge",
            Self::InvalidNonFinalPartLength => "InvalidNonFinalPartLength",
            Self::TooManyParts => "TooManyParts",
            Self::PartIndexOutOfRange => "PartIndexOutOfRange",
            Self::FrameTooShort => "FrameTooShort",
            Self::FrameTooLarge => "FrameTooLarge",
            Self::InvalidMagic => "InvalidMagic",
            Self::UnsupportedEncoding => "UnsupportedEncoding",
            Self::UnsupportedFileType => "UnsupportedFileType",
            Self::InvalidDeclaredPartCount => "InvalidDeclaredPartCount",
            Self::DeclaredPartCountExceeded => "DeclaredPartCountExceeded",
            Self::InvalidPartIndex => "InvalidPartIndex",
            Self::EmptyPart => "EmptyPart",
            Self::Base32PaddingForbidden => "Base32PaddingForbidden",
            Self::MalformedBase32Symbol => "MalformedBase32Symbol",
            Self::NonCanonicalBase32Length => "NonCanonicalBase32Length",
            Self::NonCanonicalBase32Padding => "NonCanonicalBase32Padding",
            Self::NonFinalPartLengthNotMultipleOfFive => "NonFinalPartLengthNotMultipleOfFive",
            Self::StreamEncodingMismatch => "StreamEncodingMismatch",
            Self::StreamFileTypeMismatch => "StreamFileTypeMismatch",
            Self::StreamPartCountMismatch => "StreamPartCountMismatch",
            Self::NonUniformPartLength => "NonUniformPartLength",
            Self::FinalPartTooLarge => "FinalPartTooLarge",
            Self::TotalDecodedSizeExceeded => "TotalDecodedSizeExceeded",
            Self::ConflictingDuplicate => "ConflictingDuplicate",
            Self::DuplicateWorkExceeded => "DuplicateWorkExceeded",
            Self::SubmissionWorkExceeded => "SubmissionWorkExceeded",
            Self::Incomplete => "Incomplete",
            Self::AlreadyComplete => "AlreadyComplete",
        }
    }
}

impl fmt::Display for IoRejection {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.name())
    }
}

/// Closed local shell error surface.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CoreError {
    CoreTerminated,
    InvalidTransition,
    SessionIdUnavailable,
    SessionIdExhausted,
    CapabilitiesMissing,
    CapabilitiesUnexpected,
    NoActiveFlow,
    ResponseHeaderTruncated,
    ResponseVersionMismatch,
    ResponseOpcodeMismatch,
    ResponseBodyLengthExceeded,
    ResponseBodyTruncated,
    ResponseTrailingByte,
    ResponseStatusOutOfRange,
    ResponseErrorBodyNonEmpty,
    ResponseSourceOutOfRange,
    ResponseSourceMismatch,
    ResponseTotalLengthMismatch,
    ResponseOffsetMismatch,
    ResponseChunkLengthZero,
    ResponseChunkLengthExceeded,
    ResponseTransferLengthExceeded,
    ResponseFinalOutOfRange,
    ResponseFinalMismatch,
    AllocationFailed,
    DisplayFailed,
    KeypadFailed,
    CardFailed,
    Ipc(IpcError),
    IoRejected(IoRejection),
}

impl fmt::Display for CoreError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Ipc(error) => error.fmt(formatter),
            Self::IoRejected(error) => error.fmt(formatter),
            _ => formatter.write_str(core_error_name(*self)),
        }
    }
}

impl std::error::Error for CoreError {}

impl From<IpcError> for CoreError {
    fn from(error: IpcError) -> Self {
        Self::Ipc(error)
    }
}

const fn core_error_name(error: CoreError) -> &'static str {
    match error {
        CoreError::CoreTerminated => "CoreTerminated",
        CoreError::InvalidTransition => "InvalidTransition",
        CoreError::SessionIdUnavailable => "SessionIdUnavailable",
        CoreError::SessionIdExhausted => "SessionIdExhausted",
        CoreError::CapabilitiesMissing => "CapabilitiesMissing",
        CoreError::CapabilitiesUnexpected => "CapabilitiesUnexpected",
        CoreError::NoActiveFlow => "NoActiveFlow",
        CoreError::ResponseHeaderTruncated => "ResponseHeaderTruncated",
        CoreError::ResponseVersionMismatch => "ResponseVersionMismatch",
        CoreError::ResponseOpcodeMismatch => "ResponseOpcodeMismatch",
        CoreError::ResponseBodyLengthExceeded => "ResponseBodyLengthExceeded",
        CoreError::ResponseBodyTruncated => "ResponseBodyTruncated",
        CoreError::ResponseTrailingByte => "ResponseTrailingByte",
        CoreError::ResponseStatusOutOfRange => "ResponseStatusOutOfRange",
        CoreError::ResponseErrorBodyNonEmpty => "ResponseErrorBodyNonEmpty",
        CoreError::ResponseSourceOutOfRange => "ResponseSourceOutOfRange",
        CoreError::ResponseSourceMismatch => "ResponseSourceMismatch",
        CoreError::ResponseTotalLengthMismatch => "ResponseTotalLengthMismatch",
        CoreError::ResponseOffsetMismatch => "ResponseOffsetMismatch",
        CoreError::ResponseChunkLengthZero => "ResponseChunkLengthZero",
        CoreError::ResponseChunkLengthExceeded => "ResponseChunkLengthExceeded",
        CoreError::ResponseTransferLengthExceeded => "ResponseTransferLengthExceeded",
        CoreError::ResponseFinalOutOfRange => "ResponseFinalOutOfRange",
        CoreError::ResponseFinalMismatch => "ResponseFinalMismatch",
        CoreError::AllocationFailed => "AllocationFailed",
        CoreError::DisplayFailed => "DisplayFailed",
        CoreError::KeypadFailed => "KeypadFailed",
        CoreError::CardFailed => "CardFailed",
        CoreError::Ipc(_) | CoreError::IoRejected(_) => "",
    }
}
